JuliaDiff/Diffractor.jl

src/stage1/generated.jl
Fixes the following issue,
```julia
julia> using Diffractor, LinearAlgebra
julia> loss(res, z, w) = sum(res.U * Diagonal(res.S) * res.V) + sum(res.S .* w)
loss (generic function with 1 method)
julia> Diffractor.gradient(x->loss(svd(x), x[:,1], x[:,2]), dy)^C
julia> x = randn(10, 10);
julia> Diffractor.gradient(x->loss(svd(x), x[:,1], x[:,2]), x)
ERROR: ArgumentError: indexed assignment with a single value to possibly many locations is not supported; perhaps use broadcasting `.=` instead?
Stacktrace:
[1] setindex_shape_check(::ZeroTangent, ::Int64, ::Int64)
@ Base ./indices.jl:261
[2] _unsafe_setindex!(::IndexLinear, ::Matrix{Float64}, ::ZeroTangent, ::Base.Slice{Base.OneTo{Int64}}, ::Int64)
@ Base ./multidimensional.jl:903
[3] _setindex!
@ ./multidimensional.jl:894 [inlined]
[4] setindex! …
```
=> fix array indexing backward rule

Manifest.toml, Project.toml
- add compat entries
- update dependencies
=> update dependencies and add compat

src/runtime.jl, src/stage1/forward.jl, src/stage1/generated.jl, test/runtests.jl
This wants to add methods for `rrule_via_ad` and `frule_via_ad` from ChainRules. 
~~Need to figure out how to test this; so far `rrule_via_ad` does seem to work.~~ Not sure anything is in the right place.
=> Add `RuleConfig`

src/stage1/generated.jl
Semantically these are the same.
but lets see if this works out right
=> What if `lifted_getfield` on a tangent just called `getproperty`

src/interface.jl, test/runtests.jl
Before
```
const bwd = Diffractor.PrimeDerivativeBack
bwd(bwd(x->5))
```
failed.
=> add `dx` methods

src/interface.jl, test/runtests.jl
in theory this shouldn't be necessary, but it is a good fallback to make sure we don't return thunks to the user. Also, it's 0 overhead as long as the preceding calculation is correctly inferred.
=> always unthunk results

src/extra_rules.jl, src/stage1/broadcast.jl
This should mean fewer pirate surprises if trying this out alongside Zygote/Yota.
Some of these have I think been moved to CR, so can be deleted, but not this PR. Before this PR, the following methods give warnings:
```
julia> using Diffractor
[ Info: Precompiling Diffractor [9f5e2b26-1114-432f-b630-d3fe2085c51c]
WARNING: Method definition rrule(typeof(Core.apply_type), Any, Any...) in module ChainRules at /Users/me/.julia/dev/ChainRules/src/rulesets/Core/core.jl:10 overwritten in module Diffractor at /Users/me/.julia/packages/Diffractor/shAfL/src/extra_rules.jl:140.
** incremental compilation may be fatally broken for this module **
WARNING: Method definition frule(Any, typeof(Base.getindex), AbstractArray{T, N} where N where T, Any...) in module ChainRules at …
```
=> Add `DiffractorRuleConfig` to extra `rrule`s

src/stage1/generated.jl, test/runtests.jl
This ought to return a tuple; what it returns now works in some contexts but not https://github.com/JuliaDiff/ChainRules.jl/pull/644 . 
```julia
julia> using Diffractor, ChainRulesCore
julia> ret = rrule_via_ad(Diffractor.DiffractorRuleConfig(), x -> log(exp(x)), 2)
Diffractor.OpticBundle{Float64}(2.0, (::Any)::Tuple{ZeroTangent, Any}->◌)
julia> y, bk = ret;  # ok
julia> Tuple(ret)
ERROR: MethodError: no method matching length(::Diffractor.OpticBundle{Float64})
```
Originally added in https://github.com/JuliaDiff/Diffractor.jl/pull/45, thus my fault...
=> Fix `rrule_via_ad` return type

.github/workflows/CI.yml, test/Project.toml, test/runtests.jl
This fixes nothing, but marks as broken the tests which don't pass on Julia nightly (1.9) and latest everything.
=> Mark tests broken based on nightly

.github/workflows/CI.yml, src/extra_rules.jl, src/runtime.jl, test/runtests.jl
This is a hack to fix problems like this:
```julia
g_kw(;x=1.0) = sin(x)
f_kw(x) = g_kw(;x)
@test bwd(f_kw)(1.0) == bwd(sin)(1.0)  broken=true
#=
MethodError: no method matching +(::Tangent{var"#g_kw#47"{var"#g_kw#11#48"}, NamedTuple{(Symbol("#g_kw#11"),), Tuple{ZeroTangent}}}, ::Tangent{Diffractor.KwFunc{var"#g_kw#47"{var"#g_kw#11#48"}, var"#g_kw#47##kw"}, NamedTuple{(:kwf,), Tuple{ZeroTangent}}})
...
[2] elementwise_add(a::NamedTuple{(:contents,), Tuple{Tangent{var"#g_kw#47"{var"#g_kw#11#48"}, NamedTuple{(Symbol("#g_kw#11"),), Tuple{ZeroTangent}}}}}, b::NamedTuple{(:contents,), Tuple{Tangent{Diffractor.KwFunc{var"#g_kw#47"{var"#g_kw#11#48"}, var"#g_kw#47##kw"}, NamedTuple{(:kwf,), Tuple{ZeroTangent}}}}})
@ ChainRulesCore ~/.julia/packages/ChainRulesCore/ctmSK/src/tangent_types/tangent.jl …
```
=> Accumulate NamedTuple + Tangent

src/extra_rules.jl, src/stage1/compiler_utils.jl, src/stage1/hacks.jl, src/tangent.jl
This is a quick attempt to make Diffractor work on nightly again.
=> Run on 1.9+

src/interface.jl, src/jet.jl, src/stage1/forward.jl, src/stage1/mixed.jl, src/tangent.jl, test/runtests.jl
To allow chunking like ForwardDiff.
I think this works on the Diffractor side at this point, but there's a question about the interfaces with ChainRules. In particular, to what extent do we want to want/need ChainRules to be chunking-aware. Previously ChainRules did allow tuples/arrays in its forwards rules, but we removed that support in preparation for Diffractor, because having broadcasting in the rules makes them a lot more expensive at higher orders. I think our options here are:
1. Put the broadcasting back into ChainRules
2. Have some sort of `ImplicitBroadcast` type that wraps our values and implicitly broadcasts them as appropriate (so the rules look "scalar", but actually work with chunked values).
3. Option 2 + some compiler support to implement `ImplicitBroadcast` even if the …
=> WIP: Refactor forward mode data structures

src/codegen/forward_demand.jl, src/interface.jl, src/stage1/forward.jl, src/tangent.jl
Also make the canonical 1-bundle use the TaylorBundle type. The types are isomorphic, but since `∂xⁿ{1}()` returns a TaylorBundle, this helps type stability.
=> forward_demand: Implement bundle truncation

src/jet.jl
Similar to https://github.com/JuliaLang/julia/pull/48260, this `@inbounds` hurts effects tainting.
=> Remove unnecessary `@inbounds`

src/extra_rules.jl, src/stage1/forward.jl, src/tangent.jl
None of this is particularly, pretty, but these changes help the compiler constprop things better, so let's do this for now. We can revisit in the future when the compiler learns more tricks.
=> Improve inferability of forward mode data structures

src/stage1/recurse.jl
https://github.com/JuliaLang/julia/pull/48601 added a new `VarState` struct to represent undef static params.
=> updates to work on Julia master

src/codegen/reverse.jl, test/runtests.jl
Closes #124  the cause was https://github.com/JuliaLang/julia/pull/48739
However, some of the more heavily nested AD tests segfault, so have been commented out.
I will see if fixing the other nightly break fixes them.
Failure is:
```
julia> using Diffractor
[ Info: Precompiling Diffractor [9f5e2b26-1114-432f-b630-d3fe2085c51c]
julia> var"'" = Diffractor.PrimeDerivativeBack
Diffractor.PrimeDerivativeBack
julia> sin''''(1.0)
[30984] signal (11.1): Segmentation fault
in expression starting at REPL[4]:1
_ZNK4llvm5Value7getNameEv at /home/oxinabox/dist/julia-cedar/vanilla/latest/bin/../lib/julia/libLLVM-14jl.so (unknown line)
get_pointer_to_constant at /build/julia/src/codegen.cpp:1761
stringConstPtr at /build/julia/src/cgutils.cpp:119
emit_type_error at /build/julia/src/cgutils.cpp:1359 …
```
=> fix type of nargs for making opaque closures

src/Diffractor.jl, src/codegen/reverse.jl, src/debugutils.jl, src/stage1/generated.jl, src/stage1/recurse.jl, src/stage1/recurse_fwd.jl, src/stage1/termination.jl, test/runtests.jl, test/stage2_fwd.jl
This combines #125 and #126 
(and is ontop of #123 that I merged earlier)
=> Combined nightly fixes

src/Diffractor.jl, src/stage1/generated.jl, src/stage1/recurse_fwd.jl, test/runtests.jl, test/stage2_fwd.jl
It looks like we no longer need the hack..
=> remove the hack

src/stage1/generated.jl, src/stage1/recurse_fwd.jl
We need to make sure to generate `:lambda` expression for fallback cases, otherwise we will end up with the following code generation error: <https://github.com/JuliaLang/julia/blob/38d24e574caab20529a61a6f7444c9e473724ccc/src/method.c#L603>
And now Diffractor is fully adjusted to the latest nightly build 🎉
=> follow up the `@generated` function update

src/codegen/forward_demand.jl
I wanted to add a docstring as I had no idea what `visit_custom!` did.
And then i noticed that most of the other arguments are not used
=> Document and clean sig on forward_diff_no_inf

src/codegen/forward_demand.jl, src/stage2/forward.jl, src/stage2/interpreter.jl
=> adjust to the upstream irinterp refactoring

src/tangent.jl, test/runtests.jl, test/tangent.jl
Closes #102 
I should have done this ages ago.
When digesting IR I often copy pasted it into an editor and made this change via <kbd>ctlr</kbd>+<kbd>f</kbd>. So it's clearly a good idea.
A potentially contentious change is to overload the `show` for the types themselves, but I want nice stacktraces. 
Potentially, we could do this via TruncatedStacktraces.jl?
=> Compact show for ZeroBundle etc

src/codegen/forward_demand.jl
Similar to #138. QuoteNode's value does actually need to be wrapped in ZeroBundle, otherwise it'll be at the wrong diff level.
=> Correct treatment of QuoteNode in stmt position

src/stage1/forward.jl
Same as Base.ifelse, but it's a separate generic function, so needs its own rule.
=> Add fwd rule for Core.ifelse

src/stage1/generated.jl
While trying to debug #142 ran into this which was making debugging a big more confusing.
```
julia> ∂⃖{3}()(x->"x"+x, 1)
ERROR: MethodError: no method matching (::Diffractor.∂⃖recurse{3})(::typeof(+), ::String, ::Int64)
Closest candidates are:
(::Diffractor.∂⃖recurse)(::Any...)
@ Diffractor ~/JuliaEnvs/DAECompiler.jl/dev/Diffractor/src/stage1/generated.jl:404
Stacktrace:
```
```
julia> ∂⃖{3}()(x->"x"+x, 1)
ERROR: MethodError: no method matching +(::String, ::Int64)
Closest candidates are:
+(::Any, ::Any, ::Any, ::Any...)
@ Base operators.jl:585
+(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}
@ Base int.jl:87
+(::AbstractAlgebra.MatrixElem{T}, ::Union{AbstractFloat, Integer, Rational}) where T<:Union{AbstractAlgebra.NCRingElem, …
```
=> Give correct method error

src/extra_rules.jl, src/interface.jl, src/stage1/forward.jl, src/stage1/generated.jl, src/stage1/mixed.jl
this is NFC, just removing a lot of uses of `@pure` that @keno isn't allowed to write since he isn't Jamison (and they were probably from before the effect system).
=> removes `@pure` and some miscelanious cleanups

Manifest.toml, src/codegen/forward.jl, src/codegen/forward_demand.jl, test/runtests.jl
fixes `Diffractor.PrimeDerivativeFwd(x->prod([x, 4]))(3)`. (with help from @oxinabox)
=> remove :loopinfo from IR

src/tangent.jl
We arguably should delete this method for all the reasons that you never are supposed to define these, but if we are defining it, we should at least define it right.
=> fix show `Type{<:AbstractZeroBundle}`

src/tangent.jl, test/tangent.jl
Closes #152 
It is still constructed "wrong" but we fix it in the `getindex`
Not sure if we should have `getindex(::CompositeBundle, ::TaylorTangentIndex)` calling `partial(::CompositeBundle, ::Int)`
(this PR)
or the other way around.
Which is more canonical?
We can always change later.
=> Fix getindex on CompositeBundle of a struct

src/codegen/forward_demand.jl, test/stage2_fwd.jl
This fixes a bug that @Keno  identified.
Without this fix, the attached test case errors with:
```
Unbound GlobalRef not allowed in value position
nonconst globals in forward_diff_no_inf!: Error During Test at REPL[4]:1
Got exception outside of a @test
```
There is nothing complex here, the fix is exactly as Keno described.
So I will probably just merge this as soon as CI passes
=> Don't inline accesses to nonconst globals

src/codegen/forward_demand.jl
This fixes up against recent changes in Julia nightly.
We actually need to stop marking things by setting type to any and start setting this flag at insert time.
But I will make that change in a follow up PR.
This can go in first, and it will unblock other things
=> use IR_FLAG_REFINED rather than extra_reprocess to rerun inference

src/codegen/forward_demand.jl, src/stage1/compiler_utils.jl, test/stage2_fwd.jl
This goes along with making diffractor follow this rule:
https://github.com/JuliaLang/julia/pull/50158
The hard bit of this PR was writing the test. But now I know kinda how phi-nodes work.
=> Don't insert truncation within phi blocks

src/stage1/recurse.jl
This is follow up to  JuliaLang/julia#50313
- We no longer import things that are not defined
- We do import the new `effect_free_and_nothrow` but we don't actually use it (this seemed like correct match to use previously importing `effect_free` and not using it
- we stop wrapping an instruction in `non_effect_free`. Because that is no longer defined and a similar change was made to an instruction in  JuliaLang/julia#50313 so i think it is ok, but i am not sure why it was there in the first place
=> remove noneffectfree per JuliaLang/julia#50313

test/regression.jl, test/reverse.jl, test/runtests.jl
Work around #170 
This marks over 70 tests broken.
Once that is resolved can find and replace to remove the markers. (or revert this commit)
I will merge this ASAP so can merge other stuff
=> Mark broken reverse mode tests broken

src/codegen/forward_demand.jl, src/stage2/forward.jl
We need to pass the SSA index, rather than the statement itself so that `visit_custom!()` can inspect the type of the statement under visitation.
This is more consistent with the `transform!()` API as well.
=> Pass `ssa` instead of `stmt` to `visit_custom!()`

src/codegen/forward_demand.jl, test/forward_diff_no_inf.jl
GlobalRefs often do not get their types refined, so we should be careful to re-use types that we have when possible.  This PR moves non-`const` GlobalRef handling out of `maparg()` so that we can keep the original type.
=> Improve type inference of non-`const` GlobalRef's

src/stage1/recurse.jl
This wasn't used (and broken things on older Julia versions for no reason).
=> remove `effect_free_and_nothrow`

src/codegen/forward.jl
I believe this is the correct way to detect literals. This has hit us a few times with some unexpected IR statment
=> error for nonliterals

src/stage1/forward.jl, test/forward.jl
> 🎵 I mean, what have you got to lose?
> You know, you come from nothing
> You're going back to nothing
> What have you lost? Nothing
> Nothing will come from nothing, ya know what they say 🎵
Related to the recent work by  @Keno  and @staticfloat.
By the linearity of the derivative operation if the inputs are all zero so is the output.
A case can be made that we actually should be still invoking the `frule`s for this path.
But I am not sure that's a good argument. 
Here the derivative isn't just `iszero` it has been put into the types it is zero and can't ever not be zero.
(This would not for example be the case if it were being mutated)
=> bipass all Diffractor machinery if there are no partials

Manifest.toml, src/codegen/reverse.jl, src/stage1/recurse.jl, test/regression.jl, test/reverse.jl, test/runtests.jl
This already has the error count down to 16 (from 47). The remaining issues appear to all be keyword related
=> fix reverse mode

src/codegen/forward.jl, src/codegen/reverse.jl, test/forward.jl
My previous fix was incorrect because `:boundscheck` returns a `Bool`. Let's just force it to `true` for now, which implicitly disables `@inbounds`, which is probably a good idea for us since we haven't gone through the effort of ensuring that all indexing is still valid. Add tests for this so that we catch this breakage faster next time.
=> Ensure that `:boundscheck` is properly handled

src/codegen/forward_demand.jl, src/stage2/forward.jl, test/forward_diff_no_inf.jl
In case the custom transform needs to get its argument of a particular order.
=> Pass maparg to transform

src/codegen/forward_demand.jl, src/stage1/compiler_utils.jl
This is necessary to prevent the callinfo field from falling out of sync with the call itself, causing future optimization passes (such as inlining) to compute incorrect results.
=> Use `replace_call!()` to replace `Expr(:call, ...)` values

src/codegen/forward_demand.jl, src/stage1/recurse_fwd.jl, src/stage2/forward.jl, src/tangent.jl, test/stage2_fwd.jl
To implement order-changing intrinsics.
=> Allow visit_custom recursion to change the order

src/codegen/forward_demand.jl, src/stage1/compiler_utils.jl, src/stage2/forward.jl
Follow up to #163 
It's really annoying hunting down all the places this is needed.
Currently haven't touched reverse-mode.
Definately missing some still
=> When reinference is required use IR_FLAG_REFINED

src/stage1/compiler_utils.jl, src/stage1/recurse.jl
We recently defined this in Base.
=> remove getindex definition on 1.11

src/codegen/forward_demand.jl
These are not legal to insert in-place for PhiNodes. Without this change:
```
272 ┄─ %3410  = φ (#270 => bsim4_vamodel.bsim4_module.NaN, #271 => %3409)::Incidence(Float64, )
```
is transformed into
```
272 ┄─ %3341  = (ZeroBundle{1})(bsim4_vamodel.bsim4_module.NaN)::Any
│      %3342  = φ (#270 => %3341, #271 => %3340)::Any
```
We have to reach back into the preceding basic block and insert the bundle there instead. This solution is a bit of a hack, but at least it gets things working for now.
=> Fix `ZeroBundle` wrapping for GlobalRef PhiNode args

src/AbstractDifferentiation.jl, src/stage1/compiler_utils.jl, src/stage1/forward.jl, src/stage1/recurse_fwd.jl, src/tangent.jl, test/AbstractDifferentiationTests.jl, test/forward.jl, test/tangent.jl
This is a prerequisite for  #189  as how CompositeBundle works,  causes a problem when it comes to mutation.
Right now `CompositeBundle` stores everything as a tuple of other Bundles, one per field of the primal.
Rather than storing things as a a a primal and a  tangent (or really 1 or more tangents).
This is a problem because when we need to get stuff back seperated into primal and tangent (which we need to do to apply `frules` or to actually get at the derivative result) we need to assemble the Tangent (note the capital T, this is the type that represents an immutable structural tangent)  on the fly.
Which we do here: https://github.com/JuliaDiff/Diffractor.jl/blob/ee8af85b04da82a3292cc071df9059d87d1d00fa/src/stage1/forward.jl#L8-L14
That is all well and good if everything is …
=> Remove Composite Bundle

src/tangent.jl, test/forward.jl, test/tangent.jl
This is sliced out of #221 
since that stuff is going to take a bit more thinking.
but this is an obvious and easy bug fix.
Both tests errored before these changes and now they do not.
Arguably we should delete Diffractors sepecial handling of `map` all together and leave that to ChainRules.
But that is a bigger PR.
Also requires fixing #222  (which might be easy)
=> Fix map in forwards mode

src/codegen/forward_demand.jl
The default transform should be fine.
=> forward_visit!: Don't break on stmt-level Expr(:boundscheck)

src/stage1/forward.jl, src/tangent.jl, test/tangent.jl
This PR does several things that make basically no user facing change.
It was the follow up to #224 but actually ended up way more involved.
- Adds the missing `ExplictTangentBundle[CanonicalTangentIndex(i)]`  (which is funny that it was missing as that's the natural way to index an `ExplictTangentBundle`
- Moves the `getindex` main definitions down on to to the tangent types.
- Defines promotion rules: **Explict > Taylor > Uniform**
- Defines conversions. For now only `Uniform->Taylor/Explict` and `Taylor->Explict`, though in future we could put the other way around in (but they are not always going to be defined)
- Defines equality for everything, via defining self equality and then a fallback to promotion  (apparently this is the way the julia docs recommend defining equality. I have …
=> Add polish to Bundle Types

src/tangent.jl
The problem is sometimes you will have something where the primal is also e.g. a  taylor bundle
and it prints confusingly .
Alternative solution is to use this pritty printing only when the primal is `<:Number`
=> Include outer brackets in pretty printing

src/stage1/forward.jl, test/forward.jl
Resolves #222 
I did a quick test and this didn't seem to break inference.
So I think this is fine.
I don't see reasons it shouldn't work.
But I also do not know why it was disabled in the first place.
at some point in future I think will want to AD through root-finding.
and Roots.jl uses a configured `frule` for that.
=> renable configured frules

src/tangent.jl, test/tangent.jl
This causes 10k invalidations and for example caused the loading of a downstream package to go from 13s to 36s (ref https://github.com/EnzymeAD/Enzyme.jl/issues/776).
=> stop overloading `show` on `Type`s

src/stage1/recurse.jl, src/stage2/abstractinterpret.jl, src/stage2/interpreter.jl
This is an update to make things work after https://github.com/JuliaLang/julia/pull/50943
Right now however it seems to makes tests hang
=> Update to changes to construct_ssa

src/codegen/forward.jl, test/forward.jl
this was found when doing a nasty nested AD thing.
I do think its nice that https://github.com/JuliaDiff/Diffractor.jl/pull/167 is paying off and making these easy to find and fix
=> handle Expr(:isdefined,) in forwards mode

.github/workflows/CI.yml
I guess with Diffractor tests on nightly are +/- doomed to fail, so they shouldn't get in the way of automated PR checks passing and the badge being green
See https://discourse.julialang.org/t/ignoring-nightly-failure-for-ci-badge/98028/5?u=gdalle
=> Allow CI failure on nightly

src/codegen/forward_demand.jl
Follow up to #189  I think.,
Not sure if this is correct.
=> if hit literal in forward demand use zero_tangent

src/codegen/forward.jl
Missed in #189 
Its pretty minor as its unlikely that this is being propagated but consistency is nice.
=> use zero_bundle for transform of isdefined

src/stage1/forward.jl
the surface level change in this PR is rather than using `ExplictTangentBundle` to make our bundles we us the helper function `bundle`.
`bundle` is the almost user facing function that creates the correct type of first order bundle (i.e. dual).
However the functional change of this is that in most cases we will not get `TaylorBundles` rather than `ExplictTangentBundles`.
The use of `ExplictTangentBundle` was introduced in  https://github.com/JuliaDiff/Diffractor.jl/pull/54/
However, since then we have gotten much more confortable thinking of `TaylorBundle{1}` as the normal way to represent a first derivative.
It doesn't hugely matter, since for order 1, they are exactly the same, both mathematically and in memory.
=> Don't use ExplictTangentBundle in frule_via_ad

.github/workflows/CI.yml, Project.toml, test/AbstractDifferentiationTests.jl
Potential alternative to https://github.com/JuliaDiff/Diffractor.jl/pull/228
There's something weird and wrong happening with failing tests though. If I include all the stuff into my REPL, `@test_broken` behaves properly, but if I actually do `] test` then a bunch of them propagate their failures outside of the `@test_broken` so I had to manually comment them out to get them to behave.
=> Update to new AbstractDifferentiation.jl

src/extra_rules.jl, test/extra_rules.jl, test/runtests.jl
Previously for the convertable case this errored with
```
DimensionMismatch: No precise constructor for SVector{3, Float64} found. Length of input was 1
```
This does make use of the general assumption of ChainRulesCore that Number's are their own tangent type.
But I think that is fine, that assumption exists in a whole bunch of places and if you violate it you should expect suffering.
=> Fix frule for static array constructor that converts eltype

src/stage1/forward.jl
Encountered this in the wild.
I can't however reproduce this in a simple test like
```julia
@testset "zeroed tangents intrinstics" begin
foo(x,y) = Core.Intrinsics.and_int(x, y)
z = ∂☆internal{1}()(DNEBundle{1}(foo), DNEBundle{1}(true), DNEBundle{1}(false))
@test primal(z) == foo(true, false)
@test first_partial
end
```
Not sure why. Maybe the more general handling of all DNEBundle applies there but for some reason in my real world example? 
An alternative to this is to change our general fallback handling of intrinsics to handle zeros, whether compiletime known or not
```julia
function (this::∂☆{N})(f::AbstractZeroBundle{N, Core.IntrinsicFunction}, args::ATB{N}...) where {N}
ff = primal(f)
primal_args = map(primal, args)
primal_out = ff(primal_args...)
if all(iszero, primal_args)) …
```
=> Just call primal on intrinics if all tangents are zero

src/stage1/forward.jl
This is just #282  but pointing at the `ox/for_cedar/mutation2` branch.
Discussion should be had over in #282 and this should just be merged if that one requires no changes
=> For Cedar port of handling intrinstics called with zero tangents

src/stage1/forward.jl
It's unclear whether this is a compiler bug upstream, but I've observed invokes like this in the wild:
```
%xxx = invoke DAECompiler.partial(%135::Diffractor.TangentBundle{1}, 1::Int64)::Any
```
which are (clearly) very poorly typed. `%135` was a fully concrete type, so I'm not sure why the tangent type parameters ended up getting stripped off for the invoke.
In any case, the implementations here are so small that they are probably best just inlined anyway.
=> stage1: Mark `partial` and `primal` helpers as `@inline`

src/codegen/reverse.jl, src/stage1/recurse.jl, src/stage1/recurse_fwd.jl
The feature check is done using julia#53849 (which is itself a bit of an experiment), so the idea is to merge/tag this before the base PR is merged to prevent breakage on julia master.
=> Adjust to upcoming julia#54341

src/analysis/forward.jl, src/stage1/compiler_utils.jl, src/stage1/recurse_fwd.jl, src/stage2/abstractinterpret.jl, src/stage2/lattice.jl
Only what is necessary for Cedar right now. Ordinary stage 2 reverse mode will need similar changes at a later point.
=> Adjust forward stage2 to Core.Compiler changes

src/stage2/interpreter.jl
Adjusts to a signature change in https://github.com/JuliaLang/julia/pull/57074 as in https://github.com/JuliaDebug/Cthulhu.jl/pull/627, with some cleanup on version checks to reduce complexity (essentially removing support for intermediate development versions, such as between two `-DEV.X` and `-DEV.Y` for 1.11/1.12).
=> Fix for nightly

src/stage2/interpreter.jl
Fixes a breakage introduced by a signature change in https://github.com/JuliaLang/julia/pull/58343.
Will need the same fix for 1.12 once that PR is backported.
=> Adjust to `finishinfer!` signature change

Project.toml, src/analysis/forward.jl, src/stage2/abstractinterpret.jl
https://github.com/JuliaLang/julia/pull/58131 broke a few things, which this PR aims to fix.
Some tests were already failing before this PR (and still are), but at least the intended fixes work so we can get Diffractor to successfully precompile again. @Keno feel free to merge if that looks good to you.
=> Adjust to method table changes
